services:
  api:
    build: .
    container_name: recsys_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis_db:6379/0
      - PROJECT_NAME=RecSys_Final
      - MODEL_PATH=/code/artifacts/dummy_model
    depends_on:
      - redis_db
    volumes:
      # Maps your Windows 'AnimeRec' folder to '/code' in container
      - .:/code

  redis_db:
    image: redis:7-alpine
    container_name: recsys_redis
    ports:
      - "6379:6379"

  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: recsys_qdrant
    ports:
      - "6333:6333"
