version: '3.8'

services:
  neo4j:
    image: neo4j:latest # Use a specific version for production, like neo4j:5.22.0
    container_name: neo4j
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j-data:/bitnami/neo4j
    environment:
      - NEO4J_AUTH=none # This disables authentication
      - NEO4J_server_memory_heap_max__size=10G  # Increased heap size
      - NEO4J_dbms_memory_transaction_total_max=8G # Increased total transaction memory
      - NEO4J_PLUGINS=['apoc']

volumes:
  neo4j-data:
    driver: local